### ISSUE TITLE
getMobileHeaders() function is not defined in mobiledetect.cfc

### ISSUE THREAD

**Issue by didiernactergal** [GiancarloGomez/ColdFusion-MobileDetect#1]
Do I have forget something ?

**Comment by didiernactergal** [comment]
Variable GETMOBILEHEADERS is undefined.
--

COLUMN | 0
-- | --
ID | ??
LINE | 619
RAW_TRACE | at cfMobileDetect2ecfc2007871687$funcCHECKHTTPHEADERSFORMOBILE.runFunction(E:\Sites\cfc\MobileDetect.cfc:619)
TEMPLATE | E:\Sites\cfc\MobileDetect.cfc
TYPE | CFML

**Comment by GiancarloGomez** [comment]
@didiernactergal sorry I never got around to looking at this issue. I doubt you are still experiencing this since it is so long ago so for now I am closing this issue.
